### ISSUE TITLE
sampling issues

### ISSUE THREAD

**Issue by MachineGUN001** [pengxingang/Pocket2Mol#32]
hi, 

thanks for your great effots on this highly interesting works.

when I try to run the `sample_for_pdb.py` with configs file below

```bash
model:
    checkpoint: ./ckpt/pretrained_Pocket2Mol.pt

sample:
  seed: 2023
  num_samples: 200
  beam_size: 50
  max_steps: 50
  threshold:
    focal_threshold: 0.5
    pos_threshold: 0.25
    element_threshold: 0.3
    hasatom_threshold: 0.6
    bond_threshold: 0.4
```
the script works but some errors occured, 

the error info is below
```

100%|██████████| 50/50 [00:05<00:00,  8.60it/s]
100%|██████████| 50/50 [00:05<00:00,  8.57it/s]
Traceback (most recent call last):
  File "sample_for_pdb.py", line 209, in <module>
    next_idx = np.random.choice(np.arange(n_tmp), p=prob, size=min(config.sample.beam_size, n_tmp), replace=False)
  File "mtrand.pyx", line 939, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities do not sum to 1
```

Could you please see the issue and how to fix it up?
Many Thanks,

Best,

Sh-Y

**Comment by surendraphd** [comment]
Hi,
How did you solve the above issue. I am also getting the same issue.

**Comment by MachineGUN001** [comment]
add 
```
if n_tmp <> 0:
   next_idx = np.random.choice(np.arange(n_tmp), p=prob, size=min(config.sample.beam_size, n_tmp), replace=False)
```
